In [4]:
import pandas as pd

# CSV 파일 경로 지정
file1 = '..//_ment_death_per_1000k.csv'  # 첫 번째 CSV 파일 경로
file2 = '..//_pop_by_area.csv'  # 두 번째 CSV 파일 경로

# 두 파일을 pandas DataFrame으로 읽어들임
df1 = pd.read_csv(file1)
df2 = pd.read_csv(file2)

# 첫 번째 행과 첫 번째 열을 분리하여 저장
first_row = df1.iloc[0, :]  # 첫 번째 행
first_column = df1.iloc[:, 0]  # 첫 번째 열

# 첫 번째 행과 첫 번째 열을 제외한 숫자 데이터만 가져옴
df1_numeric = df1.iloc[1:, 1:].apply(pd.to_numeric, errors='coerce')
df2_numeric = df2.iloc[1:, 1:].apply(pd.to_numeric, errors='coerce')

# 같은 행과 열에 있는 값들을 곱한 후 100000으로 나누기
result_numeric = (df1_numeric * df2_numeric) / 100000

# 첫 번째 행과 첫 번째 열의 데이터를 복원
result_numeric.insert(0, df1.columns[0], first_column.values)  # 첫 번째 열 복원
result_numeric.loc[-1] = first_row.values  # 첫 번째 행 복원
result_numeric.index = result_numeric.index + 1  # 인덱스 재정렬
result_numeric = result_numeric.sort_index()  # 인덱스를 다시 오름차순으로 정렬

# 결과를 새로운 CSV 파일로 저장
result_numeric.to_csv('result.csv', index=False)

print("CSV 파일 처리 완료. 결과는 'result.csv'에 저장되었습니다.")

ValueError: Length of values (18) does not match length of index (17)

In [3]:
import pandas as pd


df1 = pd.read_csv('..//_ment_death_per_1000k.csv')
df2 = pd.read_csv('..//_pop_by_area.csv')

# 첫 번째 행과 첫 번째 열을 제외한 숫자 데이터만 가져옴
df1_numeric = df1.iloc[1:, 1:].apply(pd.to_numeric, errors='coerce')
df2_numeric = df2.iloc[1:, 1:].apply(pd.to_numeric, errors='coerce')

# 같은 행과 열에 있는 값들을 곱한 후 100000으로 나누기
result_numeric = (df1_numeric * df2_numeric) / 100000

# 첫 번째 행과 첫 번째 열의 데이터를 복원
result = pd.DataFrame(result_numeric)
result.insert(0, df1.columns[0], df1.iloc[1:, 0].values)  # 첫 번째 열 복원
result.columns = df1.columns  # 첫 번째 행 복원

# 결과를 새로운 CSV 파일로 저장
result.to_csv('feat_ment.csv', index=False)

print("CSV 파일 처리 완료.")

CSV 파일 처리 완료.

In [ ]:
import pandas as pd


df1 = pd.read_csv('_death_per_1000k.csv')
df2 = pd.read_csv('_pop_by_area.csv')

# 첫 번째 행과 첫 번째 열을 제외한 숫자 데이터만 가져옴
df1_numeric = df1.iloc[1:, 1:].apply(pd.to_numeric, errors='coerce')
df2_numeric = df2.iloc[1:, 1:].apply(pd.to_numeric, errors='coerce')

# 같은 행과 열에 있는 값들을 곱한 후 100000으로 나누기
result_numeric = (df1_numeric * df2_numeric) / 100000

# 첫 번째 행과 첫 번째 열의 데이터를 복원
result = pd.DataFrame(result_numeric)
result.insert(0, df1.columns[0], df1.iloc[1:, 0].values)  # 첫 번째 열 복원
result.columns = df1.columns  # 첫 번째 행 복원

# 결과를 새로운 CSV 파일로 저장
result.to_csv('feat_cyc.csv', index=False)

print("CSV 파일 처리 완료.")

         AREA   2007    2008    2009    2010    2011   2012   2013  2014  \
0      ADD_UP  107.6   97.20   90.10   88.10   84.50   82.9   75.9  72.7
1       SEOUL   97.0   86.70   75.40   71.60   64.30   63.0   59.6  56.1
2       BUSAN  140.5  130.80  114.20  113.60  121.20  114.9  100.8  93.0
3       DAEGU  119.3  109.50  100.40   98.70  103.10   91.9   89.5  88.1
4     INCHEON  123.0  108.60   99.10   97.00   95.10   91.8   82.7  80.7
5     GWANGJU  106.6   92.50   87.00   82.70   78.40   79.6   69.4  76.0
6     DAEJEON  108.5   99.40   89.40   88.00   82.20   77.0   69.7  63.8
7       ULSAN  125.0  119.30  119.90  103.80  106.90  101.6   99.9  92.3
8      SEJONG  104.6  100.68   96.76   92.84   88.92   89.5   86.2  68.0
9    GYEONGGI   97.9   87.90   82.70   83.40   76.20   78.1   71.0  68.5
10    GANGWON  109.5   95.50   95.80   94.30   87.10   84.8   76.4  75.1
11   CHUNGBUK  107.5   99.60   97.20   87.80   87.00   84.1   78.7  71.9
12   CHUNGNAM   98.9   91.40   86.60   84.60   83.60   74.7   70.7  67.8
13    JEONBUK  104.0   96.50   90.60   86.50   80.90   82.5   72.4  72.2
14    JEONNAM   99.0   89.80   86.20   89.70   87.50   85.9   76.3  70.2
15  GYEONGBUK  113.4  104.40  100.60   97.30   93.20   92.2   85.5  82.4
16  GYEONGNAM  133.3  115.20  105.80  104.70  100.10  103.4   94.5  91.1
17       JEJU   89.7   73.70   63.10   60.90   59.60   63.1   62.7  55.2

    2015  2016  2017  2018  2019  2020  2021  2022  2023
0   70.7  68.0  64.9  62.9  57.3  55.9  53.4  56.0  52.6
1   58.6  56.9  55.2  55.2  49.4  48.8  48.2  49.7  45.4
2   86.9  81.3  76.9  75.4  70.5  71.6  67.5  70.2  65.9
3   87.1  84.7  74.8  72.1  59.4  60.3  56.9  59.0  51.0
4   70.5  69.6  67.6  67.3  59.1  52.6  54.0  57.2  54.7
5   78.1  68.4  65.0  65.0  55.0  50.7  47.8  49.0  45.1
6   60.6  58.5  59.8  57.2  47.8  45.9  39.7  44.3  37.7
7   96.0  86.7  74.9  80.2  74.8  75.3  71.7  70.7  64.8
8   78.6  66.1  62.6  62.7  52.8  50.8  46.8  51.4  45.8
9   65.2  65.1  63.0  60.4  56.4  53.4  51.2  53.3  50.9
10  73.8  68.3  65.7  64.0  60.3  57.8  55.1  54.9  54.9
11  69.2  70.0  65.0  61.9  59.2  57.0  52.0  55.3  53.1
12  64.5  63.2  64.5  60.0  55.5  53.5  48.7  53.6  50.7
13  66.2  67.6  65.8  54.4  55.5  53.8  50.8  56.7  57.1
14  71.6  67.0  64.2  58.4  57.3  55.9  52.2  57.2  52.2
15  80.2  73.2  68.9  63.8  60.2  63.3  59.7  62.2  58.1
16  89.2  81.7  75.8  79.2  66.3  65.0  63.3  64.8  62.0
17  49.9  54.4  50.0  53.2  46.3  42.9  49.4  51.0  49.8
         AREA          2007          2008          2009          2010  \
0      ADD_UP  4.926893e+07  4.954037e+07  4.977314e+07  5.051567e+07
1       SEOUL  1.019271e+07  1.020083e+07  1.020830e+07  1.031254e+07
2       BUSAN  3.587439e+06  3.564577e+06  3.543030e+06  3.567910e+06
3       DAEGU  2.493261e+06  2.492724e+06  2.489781e+06  2.511676e+06
4     INCHEON  2.664576e+06  2.692696e+06  2.710579e+06  2.758296e+06
5     GWANGJU  1.413444e+06  1.422702e+06  1.433640e+06  1.454636e+06
6     DAEJEON  1.475659e+06  1.480895e+06  1.484180e+06  1.503664e+06
7       ULSAN  1.099995e+06  1.112407e+06  1.114866e+06  1.126298e+06
8      SEJONG  3.990846e+03  5.986269e+03  7.981692e+03  9.977115e+03
9    GYEONGGI  1.110621e+07  1.129226e+07  1.146061e+07  1.178662e+07
10    GANGWON  1.503806e+06  1.508575e+06  1.512870e+06  1.529818e+06
11   CHUNGBUK  1.506608e+06  1.519587e+06  1.527478e+06  1.549528e+06
12   CHUNGNAM  1.995531e+06  2.018537e+06  2.037582e+06  2.075514e+06
13    JEONBUK  1.862277e+06  1.855772e+06  1.854508e+06  1.868963e+06
14    JEONNAM  1.929836e+06  1.919000e+06  1.913004e+06  1.918485e+06
15  GYEONGBUK  2.681364e+06  2.673931e+06  2.669876e+06  2.689920e+06
16  GYEONGNAM  3.196953e+06  3.225255e+06  3.250176e+06  3.290536e+06
17       JEJU  5.592580e+05  5.606180e+05  5.626630e+05  5.712550e+05

            2011      2012      2013      2014      2015      2016      2017  \
0   5.073428e+07  50948272  51141463  51327916  51529338  51696216  51778544
1   1.024968e+07  10195318  10143645  10103233  10022181   9930616   9857426
2   3.550963e+06   3538484   3527635   3519401   3513777   3498529   3470653
3   2.507271e+06   2505644   2501588   2493264   2487829   2484557   2475231
4   2.801274e+06   2843981   2879782   2902608   2925815   2943069   2948542
5   1.463464e+06   1469216   1472910   1475884   1472199   1469214   1463770
6   1.515603e+06   1524583   1532811   1531809   1518775   1514370   1502227
7   1.135494e+06   1147256   1156480   1166377   1173534   1172304   1165132
8   1.197254e+04    113117    122153    156125    210884    243048    280100
9   1.193742e+07  12093299  12234630  12357830  12522606  12716780  12873895
10  1.536448e+06   1538630   1542263   1544442   1549507   1550806   1550142
11  1.562903e+06   1565628   1572732   1578933   1583952   1591625   1594432
12  2.101284e+06   2028777   2047631   2062273   2077649   2096727   2116770
13  1.874031e+06   1873341   1872965   1871560   1869711   1864791   1854607
14  1.914339e+06   1909618   1907172   1905780   1908996   1903914   1896424
15  2.699195e+06   2698353   2699440   2700794   2702826   2700398   2691706
16  3.308765e+06   3319314   3333820   3350257   3364702   3373871   3380404
17  5.761560e+05    583713    593806    607346    624395    641597    657083

        2018      2019      2020      2021      2022      2023
0   51826059  51849861  51829023  51638809  51439038  51325329
1    9765623   9729107   9668465   9509458   9428372   9386034
2    3441453   3413841   3391946   3350380   3317812   3293362
3    2461769   2438031   2418346   2385412   2363691   2374960
4    2954642   2957026   2942828   2948375   2967314   2997410
5    1459336   1456468   1450062   1441611   1431050   1419237
6    1489936   1474870   1463882   1452251   1446072   1442216
7    1155623   1148019   1136017   1121592   1110663   1103661
8     314126    340575    355831    371895    383591    386525
9   13077153  13239666  13427014  13565450  13589432  13630821
10   1543052   1541502   1542840   1538492   1536498   1527807
11   1599252   1600007   1600837   1597427   1595058   1593469
12   2126282   2123709   2121029   2119257   2123037   2130119
13   1836832   1818917   1804104   1786855   1769607   1754757
14   1882970   1868745   1851549   1832803   1817697   1804217
15   2676831   2665836   2639422   2626609   2600492   2554324
16   3373988   3362553   3340216   3314183   3280493   3251158
17    667191    670989    674635    676759    678159    675252
     2007    2008    2009    2010    2011   2012   2013  2014  2015  2016  \
1    97.0   86.70   75.40   71.60   64.30   63.0   59.6  56.1  58.6  56.9
2   140.5  130.80  114.20  113.60  121.20  114.9  100.8  93.0  86.9  81.3
3   119.3  109.50  100.40   98.70  103.10   91.9   89.5  88.1  87.1  84.7
4   123.0  108.60   99.10   97.00   95.10   91.8   82.7  80.7  70.5  69.6
5   106.6   92.50   87.00   82.70   78.40   79.6   69.4  76.0  78.1  68.4
6   108.5   99.40   89.40   88.00   82.20   77.0   69.7  63.8  60.6  58.5
7   125.0  119.30  119.90  103.80  106.90  101.6   99.9  92.3  96.0  86.7
8   104.6  100.68   96.76   92.84   88.92   89.5   86.2  68.0  78.6  66.1
9    97.9   87.90   82.70   83.40   76.20   78.1   71.0  68.5  65.2  65.1
10  109.5   95.50   95.80   94.30   87.10   84.8   76.4  75.1  73.8  68.3
11  107.5   99.60   97.20   87.80   87.00   84.1   78.7  71.9  69.2  70.0
12   98.9   91.40   86.60   84.60   83.60   74.7   70.7  67.8  64.5  63.2
13  104.0   96.50   90.60   86.50   80.90   82.5   72.4  72.2  66.2  67.6
14   99.0   89.80   86.20   89.70   87.50   85.9   76.3  70.2  71.6  67.0
15  113.4  104.40  100.60   97.30   93.20   92.2   85.5  82.4  80.2  73.2
16  133.3  115.20  105.80  104.70  100.10  103.4   94.5  91.1  89.2  81.7
17   89.7   73.70   63.10   60.90   59.60   63.1   62.7  55.2  49.9  54.4

    2017  2018  2019  2020  2021  2022  2023
1   55.2  55.2  49.4  48.8  48.2  49.7  45.4
2   76.9  75.4  70.5  71.6  67.5  70.2  65.9
3   74.8  72.1  59.4  60.3  56.9  59.0  51.0
4   67.6  67.3  59.1  52.6  54.0  57.2  54.7
5   65.0  65.0  55.0  50.7  47.8  49.0  45.1
6   59.8  57.2  47.8  45.9  39.7  44.3  37.7
7   74.9  80.2  74.8  75.3  71.7  70.7  64.8
8   62.6  62.7  52.8  50.8  46.8  51.4  45.8
9   63.0  60.4  56.4  53.4  51.2  53.3  50.9
10  65.7  64.0  60.3  57.8  55.1  54.9  54.9
11  65.0  61.9  59.2  57.0  52.0  55.3  53.1
12  64.5  60.0  55.5  53.5  48.7  53.6  50.7
13  65.8  54.4  55.5  53.8  50.8  56.7  57.1
14  64.2  58.4  57.3  55.9  52.2  57.2  52.2
15  68.9  63.8  60.2  63.3  59.7  62.2  58.1
16  75.8  79.2  66.3  65.0  63.3  64.8  62.0
17  50.0  53.2  46.3  42.9  49.4  51.0  49.8
            2007          2008          2009          2010          2011  \
1   1.019271e+07  1.020083e+07  1.020830e+07  1.031254e+07  1.024968e+07
2   3.587439e+06  3.564577e+06  3.543030e+06  3.567910e+06  3.550963e+06
3   2.493261e+06  2.492724e+06  2.489781e+06  2.511676e+06  2.507271e+06
4   2.664576e+06  2.692696e+06  2.710579e+06  2.758296e+06  2.801274e+06
5   1.413444e+06  1.422702e+06  1.433640e+06  1.454636e+06  1.463464e+06
6   1.475659e+06  1.480895e+06  1.484180e+06  1.503664e+06  1.515603e+06
7   1.099995e+06  1.112407e+06  1.114866e+06  1.126298e+06  1.135494e+06
8   3.990846e+03  5.986269e+03  7.981692e+03  9.977115e+03  1.197254e+04
9   1.110621e+07  1.129226e+07  1.146061e+07  1.178662e+07  1.193742e+07
10  1.503806e+06  1.508575e+06  1.512870e+06  1.529818e+06  1.536448e+06
11  1.506608e+06  1.519587e+06  1.527478e+06  1.549528e+06  1.562903e+06
12  1.995531e+06  2.018537e+06  2.037582e+06  2.075514e+06  2.101284e+06
13  1.862277e+06  1.855772e+06  1.854508e+06  1.868963e+06  1.874031e+06
14  1.929836e+06  1.919000e+06  1.913004e+06  1.918485e+06  1.914339e+06
15  2.681364e+06  2.673931e+06  2.669876e+06  2.689920e+06  2.699195e+06
16  3.196953e+06  3.225255e+06  3.250176e+06  3.290536e+06  3.308765e+06
17  5.592580e+05  5.606180e+05  5.626630e+05  5.712550e+05  5.761560e+05

        2012      2013      2014      2015      2016      2017      2018  \
1   10195318  10143645  10103233  10022181   9930616   9857426   9765623
2    3538484   3527635   3519401   3513777   3498529   3470653   3441453
3    2505644   2501588   2493264   2487829   2484557   2475231   2461769
4    2843981   2879782   2902608   2925815   2943069   2948542   2954642
5    1469216   1472910   1475884   1472199   1469214   1463770   1459336
6    1524583   1532811   1531809   1518775   1514370   1502227   1489936
7    1147256   1156480   1166377   1173534   1172304   1165132   1155623
8     113117    122153    156125    210884    243048    280100    314126
9   12093299  12234630  12357830  12522606  12716780  12873895  13077153
10   1538630   1542263   1544442   1549507   1550806   1550142   1543052
11   1565628   1572732   1578933   1583952   1591625   1594432   1599252
12   2028777   2047631   2062273   2077649   2096727   2116770   2126282
13   1873341   1872965   1871560   1869711   1864791   1854607   1836832
14   1909618   1907172   1905780   1908996   1903914   1896424   1882970
15   2698353   2699440   2700794   2702826   2700398   2691706   2676831
16   3319314   3333820   3350257   3364702   3373871   3380404   3373988
17    583713    593806    607346    624395    641597    657083    667191

        2019      2020      2021      2022      2023
1    9729107   9668465   9509458   9428372   9386034
2    3413841   3391946   3350380   3317812   3293362
3    2438031   2418346   2385412   2363691   2374960
4    2957026   2942828   2948375   2967314   2997410
5    1456468   1450062   1441611   1431050   1419237
6    1474870   1463882   1452251   1446072   1442216
7    1148019   1136017   1121592   1110663   1103661
8     340575    355831    371895    383591    386525
9   13239666  13427014  13565450  13589432  13630821
10   1541502   1542840   1538492   1536498   1527807
11   1600007   1600837   1597427   1595058   1593469
12   2123709   2121029   2119257   2123037   2130119
13   1818917   1804104   1786855   1769607   1754757
14   1868745   1851549   1832803   1817697   1804217
15   2665836   2639422   2626609   2600492   2554324
16   3362553   3340216   3314183   3280493   3251158
17    670989    674635    676759    678159    675252
            2007         2008         2009         2010         2011  \
1    9886.928700  8844.117009  7697.059708  7383.782220  6590.543597
2    5040.351795  4662.466716  4046.140260  4053.145760  4303.767156
3    2974.460373  2729.532780  2499.740124  2479.024212  2584.996401
4    3277.428480  2924.267856  2686.183789  2675.547120  2664.011574
5    1506.731304  1315.999350  1247.266800  1202.983972  1147.355776
6    1601.090015  1472.009630  1326.856920  1323.224320  1245.825666
7    1374.993750  1327.101551  1336.724334  1169.097324  1213.843086
8       4.174425     6.026976     7.723085     9.262754    10.645981
9   10872.980569  9925.900056  9477.924470  9830.042748  9096.310230
10   1646.667570  1440.689125  1449.329460  1442.618374  1338.246208
11   1619.603600  1513.508652  1484.708616  1360.485584  1359.725610
12   1973.580159  1844.942818  1764.546012  1755.884844  1756.673424
13   1936.768080  1790.819980  1680.184248  1616.652995  1516.091079
14   1910.537640  1723.262000  1649.009448  1720.881045  1675.046625
15   3040.666776  2791.583964  2685.895256  2617.292160  2515.649740
16   4261.538349  3715.493760  3438.686208  3445.191192  3312.073765
17    501.654426   413.175466   355.040353   347.894295   343.388976

           2012         2013         2014         2015         2016  \
1   6423.050340  6045.612420  5667.913713  5872.998066  5650.520504
2   4065.718116  3555.856080  3273.042930  3053.472213  2844.304077
3   2302.686836  2238.921260  2196.565584  2166.899059  2104.419779
4   2610.774558  2381.579714  2342.404656  2062.699575  2048.376024
5   1169.495936  1022.199540  1121.671840  1149.787419  1004.942376
6   1173.928910  1068.369267   977.294142   920.377650   885.906450
7   1165.612096  1155.323520  1076.565971  1126.592640  1016.387568
8    101.239715   105.295886   106.165000   165.754824   160.654728
9   9444.866519  8686.587300  8465.113550  8164.739112  8278.623780
10  1304.758240  1178.288932  1159.875942  1143.536166  1059.200498
11  1316.693148  1237.740084  1135.252827  1096.094784  1114.137500
12  1515.496419  1447.675117  1398.221094  1340.083605  1325.131464
13  1545.506325  1356.026660  1351.266320  1237.748682  1260.598716
14  1640.361862  1455.172236  1337.857560  1366.841136  1275.622380
15  2487.881466  2308.021200  2225.454256  2167.666452  1976.691336
16  3432.170676  3150.459900  3052.084127  3001.314184  2756.452607
17   368.322903   372.316362   335.254992   311.573105   349.028768

           2017         2018         2019         2020         2021  \
1   5441.299152  5390.623896  4806.178858  4718.210920  4583.558756
2   2668.932157  2594.855562  2406.757905  2428.633336  2261.506500
3   1851.472788  1774.935449  1448.190414  1458.262638  1357.299428
4   1993.214392  1988.474066  1747.602366  1547.927528  1592.122500
5    951.450500   948.568400   801.057400   735.181434   689.090058
6    898.331746   852.243392   704.987860   671.921838   576.543647
7    872.683868   926.809646   858.718212   855.420801   804.181464
8    175.342600   196.957002   179.823600   180.762148   174.046860
9   8110.553850  7898.600412  7467.171624  7170.025476  6945.510400
10  1018.443294   987.553280   929.525706   891.761520   847.709092
11  1036.380800   989.936988   947.204144   912.477090   830.662040
12  1365.316650  1275.769200  1178.658495  1134.750515  1032.078159
13  1220.331406   999.236608  1009.498935   970.607952   907.722340
14  1217.504208  1099.654480  1070.790885  1035.015891   956.723166
15  1854.585434  1707.818178  1604.833272  1670.754126  1568.085573
16  2562.346232  2672.198496  2229.372639  2171.140400  2097.877839
17   328.541500   354.945612   310.667907   289.418415   334.318946

           2022         2023
1   4685.900884  4261.259436
2   2329.104024  2170.325558
3   1394.577690  1211.229600
4   1697.303608  1639.583270
5    701.214500   640.075887
6    640.609896   543.715432
7    785.238741   715.172328
8    197.165774   177.028450
9   7243.167256  6938.087889
10   843.537402   838.766043
11   882.067074   846.132039
12  1137.947832  1079.970333
13  1003.367169  1001.966247
14  1039.722684   941.801274
15  1617.506024  1484.062244
16  2125.759464  2015.717960
17   345.861090   336.275496
         AREA          2007         2008         2009         2010  \
1       SEOUL   9886.928700  8844.117009  7697.059708  7383.782220
2       BUSAN   5040.351795  4662.466716  4046.140260  4053.145760
3       DAEGU   2974.460373  2729.532780  2499.740124  2479.024212
4     INCHEON   3277.428480  2924.267856  2686.183789  2675.547120
5     GWANGJU   1506.731304  1315.999350  1247.266800  1202.983972
6     DAEJEON   1601.090015  1472.009630  1326.856920  1323.224320
7       ULSAN   1374.993750  1327.101551  1336.724334  1169.097324
8      SEJONG      4.174425     6.026976     7.723085     9.262754
9    GYEONGGI  10872.980569  9925.900056  9477.924470  9830.042748
10    GANGWON   1646.667570  1440.689125  1449.329460  1442.618374
11   CHUNGBUK   1619.603600  1513.508652  1484.708616  1360.485584
12   CHUNGNAM   1973.580159  1844.942818  1764.546012  1755.884844
13    JEONBUK   1936.768080  1790.819980  1680.184248  1616.652995
14    JEONNAM   1910.537640  1723.262000  1649.009448  1720.881045
15  GYEONGBUK   3040.666776  2791.583964  2685.895256  2617.292160
16  GYEONGNAM   4261.538349  3715.493760  3438.686208  3445.191192
17       JEJU    501.654426   413.175466   355.040353   347.894295

           2011         2012         2013         2014         2015  \
1   6590.543597  6423.050340  6045.612420  5667.913713  5872.998066
2   4303.767156  4065.718116  3555.856080  3273.042930  3053.472213
3   2584.996401  2302.686836  2238.921260  2196.565584  2166.899059
4   2664.011574  2610.774558  2381.579714  2342.404656  2062.699575
5   1147.355776  1169.495936  1022.199540  1121.671840  1149.787419
6   1245.825666  1173.928910  1068.369267   977.294142   920.377650
7   1213.843086  1165.612096  1155.323520  1076.565971  1126.592640
8     10.645981   101.239715   105.295886   106.165000   165.754824
9   9096.310230  9444.866519  8686.587300  8465.113550  8164.739112
10  1338.246208  1304.758240  1178.288932  1159.875942  1143.536166
11  1359.725610  1316.693148  1237.740084  1135.252827  1096.094784
12  1756.673424  1515.496419  1447.675117  1398.221094  1340.083605
13  1516.091079  1545.506325  1356.026660  1351.266320  1237.748682
14  1675.046625  1640.361862  1455.172236  1337.857560  1366.841136
15  2515.649740  2487.881466  2308.021200  2225.454256  2167.666452
16  3312.073765  3432.170676  3150.459900  3052.084127  3001.314184
17   343.388976   368.322903   372.316362   335.254992   311.573105

           2016         2017         2018         2019         2020  \
1   5650.520504  5441.299152  5390.623896  4806.178858  4718.210920
2   2844.304077  2668.932157  2594.855562  2406.757905  2428.633336
3   2104.419779  1851.472788  1774.935449  1448.190414  1458.262638
4   2048.376024  1993.214392  1988.474066  1747.602366  1547.927528
5   1004.942376   951.450500   948.568400   801.057400   735.181434
6    885.906450   898.331746   852.243392   704.987860   671.921838
7   1016.387568   872.683868   926.809646   858.718212   855.420801
8    160.654728   175.342600   196.957002   179.823600   180.762148
9   8278.623780  8110.553850  7898.600412  7467.171624  7170.025476
10  1059.200498  1018.443294   987.553280   929.525706   891.761520
11  1114.137500  1036.380800   989.936988   947.204144   912.477090
12  1325.131464  1365.316650  1275.769200  1178.658495  1134.750515
13  1260.598716  1220.331406   999.236608  1009.498935   970.607952
14  1275.622380  1217.504208  1099.654480  1070.790885  1035.015891
15  1976.691336  1854.585434  1707.818178  1604.833272  1670.754126